server:
  port: 8090
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full


