---
logging:
  level:
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    com.zaxxer.hikari: ERROR
    access: DEBUG

server:
  error:
    path: "/error"
    include-message: always
  forward-headers-strategy: framework

spring:
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
    timeout: 8h
  mvc:
    log-request-details: false
  security:
    oauth2:
      client:
        registration:
          oidcng:
            client-id: playground_client
            client-secret: secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: "authorization_code"
            scope: openid
        provider:
          oidcng:
            authorization-uri: "https://connect.test2.surfconext.nl/oidc/authorize"
            token-uri: "https://connect.test2.surfconext.nl/oidc/token"
            user-info-uri: "https://connect.test2.surfconext.nl/oidc/userinfo"
            jwk-set-uri: "https://connect.test2.surfconext.nl/oidc/certs"
            user-name-attribute: sub
            user-info-authentication-method: client_secret_basic
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/access
    username: access
    password: secret
  flyway:
    locations: classpath:db/{vendor}/migration
    fail-on-missing-locations: true
  mail:
    host: localhost
    port: 3025

cron:
  node-cron-job-responsible: true
  user-cleaner-expression: "0 0/30 * * * *"
  last-activity-duration-days: 1000
  role-expiration-notifier-expression: "0 0/30 * * * *"
  # Set to -1 to suppress role expiry notifications
  role-expiration-notifier-duration-days: 5

oidcng:
  discovery-url: "https://connect.test2.surfconext.nl/oidc/.well-known/openid-configuration"
  introspect-url: "https://connect.test2.surfconext.nl/oidc/introspect"
  resource-server-id: myconext.rs
  resource-server-secret: secret
  base-url: http://localhost:8080

super-admin:
  users:
    - "urn:collab:person:example.com:admin"

config:
  client-url: "http://localhost:3000"
  welcome-url: "http://localhost:4000"
  server-url: "http://localhost:8080"
  server-welcome-url: "http://localhost:8080"
  eduid-entity-id: "https://login.test2.eduid.nl"
  role-search-required: false

voot:
  user: voot
  password: secret
  group_urn_domain: urn:mace:surf.nl:test.surfaccess.nl

attribute-aggregation:
  user: aa
  password: secret

email:
  from: "no-reply@surf.nl"
  contactEmail: "access@surf.nl"
  environment: "local"
  enabled: false

manage:
  enabled: false
  url: "https://manage.test2.surfconext.nl"
  user: access
  password: secret

springdoc:
  pathsToMatch: "/api/external/v1/**"
  api-docs:
    path: "/ui/api-docs"
  swagger-ui:
    path: "/ui/api-ui.html"
    operationsSorter: method
    oauth:
      client-id: ${spring.security.oauth2.client.registration.oidcng.client-id}
      client-secret: ${spring.security.oauth2.client.registration.oidcng.client-secret}
      use-basic-authentication-with-access-code-grant: true


management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info,mappings"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    mappings:
      enabled: true
  info:
    git:
      mode: full
