---

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO

environment: local
mock-server-base-url: http://localhost:8081
invite-server-ms-redirect-url: http://localhost:8080/api/v1/users/ms-accept-return

spring:
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/access
    username: access
    password: secret

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,mappings"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full
