name: build-push-docker-image

on:
  workflow_call:

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the server image
        uses: docker/build-push-action@v4
        with:
          context: server
          file: server/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/openconext/openconext-access/accessserver:latest
