name: Deploy

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deployment:
    environment: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Maven
      uses: stCarolas/setup-maven@v.4.5
      with:
        maven-version: 3.8.7
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        server-id: openconext-snapshots
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Check settings.xml
      run: cat $HOME/.m2/settings.xml
    - name: Deploy with Maven
      run: mvn --batch-mode deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.BUILD_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.BUILD_PASSWORD }}
  build-push-docker-image:       
      needs: deployment
      uses: ./.github/workflows/build-push-docker-image.yml

