name: Maven install

on:
  workflow_dispatch:
    
jobs:
  deployment:
    permissions:
      packages: write
    environment: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Maven
      uses: stCarolas/setup-maven@v.4.5
      with:
        maven-version: 3.8.7
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        server-id: openconext-snapshots
    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Deploy with Maven
      run: mvn --batch-mode install -DskipTests
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push the server image
      uses: docker/build-push-action@v4
      with:
        context: server
        file: server/docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/openconext/openconext-access/accessserver:latest
